#!/usr/bin/php -q
<?php 
/***************************************************************************
 *            a2billing_bill_diduse.php
 *
 *  Fri Oct 28 11:51:08 2005
 *  Copyright  2005  User
 *  ADD THIS SCRIPT IN A CRONTAB JOB
 *
	crontab -e
	0 12 * * * php /var/lib/asterisk/agi-bin/libs_a2billing/crontjob/a2billing_bill_diduse.php
	
	
	# crontab -l
	# DO NOT EDIT THIS FILE - edit the master and reinstall.
	# (/tmp/crontab.9543 installed on Fri Oct 28 04:44:10 2005)
	# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
	0 12 * * * php /var/lib/asterisk/agi-bin/libs_a2billing/crontjob/a2billing_bill_diduse.php
****************************************************************************/
	set_time_limit(0);
	error_reporting(E_ALL ^ (E_NOTICE | E_WARNING));
	
	include (dirname(__FILE__)."/../defines.php");
	include (dirname(__FILE__)."/../db_php_lib/Class.Table.php");
	include (dirname(__FILE__)."/../Class.A2Billing.php");
	
	
	$verbose_level=1;
	
	$groupcard=5000;
	
	function write_log($output, $tobuffer = 1){
			
			$string_log = "[".date("d/m/Y H:i:s")."]:$output\n";
			error_log ($string_log, 3, BATCH_LOG_FILE);
						
	}
	
	if ($A2B->config["database"]['dbtype'] == "postgres"){
	        $UNIX_TIMESTAMP = "date_part('epoch',";
	}else{
	        $UNIX_TIMESTAMP = "UNIX_TIMESTAMP(";
	}
	
	write_log("[#### BATCH BEGIN ####]");
	
	
	$A2B = new A2Billing();
	$A2B -> load_conf($agi, NULL, 0, $idconfig);
	
	if (!$A2B -> DbConnect()){				
				echo "[Cannot connect to the database]\n";
				write_log("[Cannot connect to the database]");
				exit;						
	}
	//$A2B -> DBHandle
	$instance_table = new Table();
	
	// CHECK THE CARD WITH DID'S
	$QUERY = 'SELECT id_did,reservationdate,month_payed,fixrate,cc_card.id,credit,email FROM (cc_did_use INNER JOIN cc_card on cc_card.id=id_cc_card) INNER JOIN cc_did ON (id_did=cc_did.id) WHERE releasedate IS NULL AND cc_did_use.activated=1';

	if ($verbose_level>=1) echo "==> SELECT CARD WIHT DID'S QUERY : $QUERY\n";
	$result = $instance_table -> SQLExec ($A2B -> DBHandle, $QUERY);
	
	if ($verbose_level>=1) print_r ($result);
	
	if( !is_array($result)) {
		if ($verbose_level>=1) echo "[No card to run the did use bill recurring service]\n";
		write_log("[ No card to run the did use bill recurring service]");
		exit();
	}
	
	$oneday = 60*60*24;
	// count day that user have to recharge his account
	$daytopay=5;


	// BROWSE THROUGH THE CARD TO APPLY THE DID USAGE
	foreach ($result as $mydids){

		// mail variable for user notification
		$user_mail_adrr = '';
        $mail_user = false;
		$mail_user_content = '';
		
		if ($verbose_level>=1) print_r ($mydids);
		if ($verbose_level>=1) echo "------>>>  ID DID = ".$mydids[0]." - FIXERATE = ".$mydids[3]."ID CARD = ".$mydids[4]." -BALANCE =".$mycard[5]." \n";	
		$day_remaining = 0;
		$timestamp_datetopay = mktime(date('H',(strtotime($mydids[1]))-(intval($daytopay) * $oneday)),
										date("i",(strtotime($mydids[1]))-(intval($daytopay) * $oneday)),
										date("s",(strtotime($mydids[1]))-(intval($daytopay) * $oneday)),
										date("m",(strtotime($mydids[1]))-(intval($daytopay) * $oneday))+$mydids[2],
										date("d",(strtotime($mydids[1]))-(intval($daytopay) * $oneday)),
										date("Y",(strtotime($mydids[1]))-(intval($daytopay) * $oneday)));
		
		$day_remaining = time() - $timestamp_datetopay;
		if ($verbose_level>=1) echo $day_remaining."<=".(intval($daytopay) * $oneday)."\n";
			if ($day_remaining >= 0)
			{
				if ($day_remaining<=(intval($daytopay) * $oneday))
				{
					if ($mydids[5] >= $mydids[3])
					{
						$QUERY = "UPDATE cc_card SET credit=credit-'".$mydids[3]."' WHERE id=".$mydids[4];	
						$result = $instance_table -> SQLExec ($A2B -> DBHandle, $QUERY, 0);
						if ($verbose_level>=1) echo "==> UPDATE CARD QUERY: 	$QUERY\n";
						
						$QUERY = "UPDATE cc_did_use set month_payed = month_payed+1 WHERE id_did = '".$mydids[0]."' AND activated = 1 AND releasedate IS NULL" ;
						if ($verbose_level>=1) echo "==> UPDATE DID USE QUERY: 	$QUERY\n";
						$result = $instance_table -> SQLExec ($A2B -> DBHandle, $QUERY, 0);
						
						$QUERY = "INSERT INTO cc_charge (id_cc_card, amount, chargetype,id_cc_did) VALUES ('".$mydids[4]."', '".$mydids[3]."', '2','".$mydids[0]."')";
						if ($verbose_level>=1) echo "==> INSERT CHARGE QUERY: 	$QUERY\n";
						$result = $instance_table -> SQLExec ($A2B -> DBHandle, $QUERY, 0);
						
						$mail_user_content.="BALANCE REMAINING ".$mydids[5]-$mydids[3]."\n\n";
						$mail_user_content.="A automaticly taking away of :".$mydids[3]." has been carry out of your acount \n\n";	
						$mail_user_content.="Monthly Fixrate for DID :".$mydids[0]."\n\n";
						$mail_user=true;
						$mail_user_subject="DID notification";
					} else {
						$mail_user_content.="BALANCE REMAINING ".$mydids[5]."\n\n";
						$mail_user_content.="Your credit is not enouf to pay did number :".$mydids[0]."\n\n";
						$mail_user_content.="You have ".date ("d",$day_remaining)." days to recharge your card, or the did will be automaticly unreserved \n\n";
						$mail_user=true;
						$mail_user_subject="DID notification";
					}	
				}
			} else {
					$QUERY = "UPDATE cc_did set iduser = 0, reserved = 0 WHERE id='".$mydids[0]."'" ;
					$result = $instance_table -> SQLExec ($A2B -> DBHandle, $QUERY, 0);
					$QUERY1 = "UPDATE cc_did_use set releasedate = now() where id_did = '".$mydids[0]."' and activated = 1" ;
					$result = $instance_table -> SQLExec ($A2B -> DBHandle, $QUERY, 0);
					$QUERY = "INSERT INTO cc_did_use (activated, id_did) values ('0','".$mydids[0]."')";
					$result = $instance_table -> SQLExec ($A2B -> DBHandle, $QUERY, 0);
					$QUERY = "DELETE FROM cc_did_destination where id_cc_did =".$mydids[0];
					$result = $instance_table -> SQLExec ($A2B -> DBHandle, $QUERY, 0);
					$mail_user_content.="The did ".$mydids[0]." has been automaticly unreserved\n\n";
					$mail_user=true;
					$mail_user_subject="DID last notification";
				}
			$user_mail_adrr=$mydids[6];
			if ($mail_user) mail($user_mail_adrr, $mail_user_subject, $mail_content);
		}
	write_log("[Service finish]");
	
	if ($verbose_level>=1) echo "#### END RECURRING SERVICES \n";

	write_log("[#### BATCH PROCESS END ####]");
	
?>
